import type { Metadata } from 'next'
import "./globals.css"
import { ClientFormProvider } from '@/providers/FormProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className='max-w-[768px] mx-auto'>
      <body>
        <ClientFormProvider>
          {children}
        </ClientFormProvider>
      </body>
    </html>
  )
}
